### ISSUE TITLE
Crash at date 01/01/2014

### ISSUE THREAD

**Issue by CodingTarik** [khalidabuhakmeh/MoonPhaseConsole#1]
Your code is not working for some dates. I used the following unit test:

```c# 
[TestMethod("Moonsphere Calculation 2")]
        public void TestMoonphase2()
        {          
            Debug.WriteLine("TODAY: " + MoonTest.Calculate(DateTime.Now).Name);
            for (int i = 0; i <= 20; i++)
            {
                Debug.WriteLine("Testing: " + "01/01/:" + (2000 + i));
                Debug.WriteLine("Result: " + MoonTest.Calculate(new DateTime(i + 2000, 1, 1)).Name);
            }
        }
```

Error: " Test method Pangolin_Database_Unit_Tests.UnitTests.TestMoonphase2 threw exception: 
    System.InvalidOperationException: Sequence contains no elements"

Stacktrace: " ThrowHelper.ThrowNoElementsException()
    Enumerable.First[TSource](IEnumerable`1 source)
    MoonTest.Calculate(DateTime utcDateTime, Hemispheres viewFromEarth) Zeile 68
    UnitTests.TestMoonphase2() Zeile 41"

"Debug Trace:
TODAY: New Moon
Testing: 01/01/:2000
Result: Waning Crescent
Testing: 01/01/:2001
Result: First Quarter
Testing: 01/01/:2002
Result: Waning Gibbous
Testing: 01/01/:2003
Result: New Moon
Testing: 01/01/:2004
Result: Waxing Gibbous
Testing: 01/01/:2005
Result: Third Quarter
Testing: 01/01/:2006
Result: Waxing Crescent
Testing: 01/01/:2007
Result: Full Moon
Testing: 01/01/:2008
Result: Waning Crescent
Testing: 01/01/:2009
Result: First Quarter
Testing: 01/01/:2010
Result: Waning Gibbous
Testing: 01/01/:2011
Result: New Moon
Testing: 01/01/:2012
Result: Waxing Gibbous
Testing: 01/01/:2013
Result: Third Quarter
Testing: 01/01/:2014"

So it is crashing for 01/01/2014

**Comment by khalidabuhakmeh** [comment]
@CodingTarik Hi, I just pushed up a fix. It seems manually setting boundaries for moon phases was a bad idea. I just divided the phases equally across the `29.5` day cycle. It should be good now I believe.
